/**
 * @file Test helpers: load fixture documents through the same pipeline as live extraction, and
 * build a fake model client.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { confirmBill, confirmEob } from "@/lib/extract/confirm";
import { extractFromSavedReply } from "@/lib/extract/pipeline";
import type { LlmClient } from "@/lib/llm";
import type { ConfirmedBill, ConfirmedEob, ExtractedBill, ExtractedEob } from "@/lib/types";

/** Fixture names generated by `npm run fixtures`. */
export type FixtureName = "sample-bill" | "sample-eob" | "balance-statement" | "bill-broken-totals" | "bill-injection";

/**
 * Reads a fixture PDF.
 *
 * @param name - Fixture name.
 * @returns PDF bytes.
 */
export function fixturePdf(name: FixtureName): Uint8Array {
  return new Uint8Array(readFileSync(join(process.cwd(), "fixtures", "documents", `${name}.pdf`)));
}

/**
 * Reads a fixture's expected raw model reply.
 *
 * @param name - Fixture name.
 * @returns Parsed JSON reply.
 */
export function fixtureReply(name: FixtureName): unknown {
  return JSON.parse(readFileSync(join(process.cwd(), "fixtures", "llm-output", `${name}.json`), "utf8"));
}

/**
 * Extracts a fixture bill via the saved-reply path (with the text-layer check).
 *
 * @param name - Bill fixture name.
 * @returns The checked bill.
 */
export async function extractedBill(name: FixtureName): Promise<ExtractedBill> {
  const r = await extractFromSavedReply(fixtureReply(name), fixturePdf(name));
  if (r.kind !== "bill") throw new Error(`${name} is not a bill`);
  return r.bill;
}

/**
 * Extracts the fixture EOB.
 *
 * @returns The checked EOB.
 */
export async function extractedEob(): Promise<ExtractedEob> {
  const r = await extractFromSavedReply(fixtureReply("sample-eob"), fixturePdf("sample-eob"));
  if (r.kind !== "eob") throw new Error("sample-eob is not an EOB");
  return r.eob;
}

/**
 * Confirms the sample bill with no corrections.
 *
 * @returns The confirmed sample bill.
 */
export async function confirmedSampleBill(): Promise<ConfirmedBill> {
  const r = confirmBill(await extractedBill("sample-bill"), { documentId: "doc_bill", corrections: {}, confirmedPaths: [], acknowledgeTotalsMismatch: false });
  if (!r.ok) throw new Error(r.blocking.join("; "));
  return r.value;
}

/**
 * Confirms the sample EOB with no corrections.
 *
 * @returns The confirmed sample EOB.
 */
export async function confirmedSampleEob(): Promise<ConfirmedEob> {
  const r = confirmEob(await extractedEob(), { documentId: "doc_eob", corrections: {}, confirmedPaths: [], acknowledgeTotalsMismatch: false });
  if (!r.ok) throw new Error(r.blocking.join("; "));
  return r.value;
}

/**
 * Builds a fake model client that returns queued replies in order and records each request.
 *
 * @param replies - Reply texts (JSON strings or junk) returned in order.
 * @returns The client and the list of requests it received.
 */
export function fakeClient(replies: string[]): { client: LlmClient; requests: Array<Parameters<LlmClient["complete"]>[0]> } {
  const requests: Array<Parameters<LlmClient["complete"]>[0]> = [];
  const queue = [...replies];
  return {
    requests,
    client: {
      async complete(args) {
        requests.push(args);
        const next = queue.shift();
        if (next === undefined) throw new Error("fake client ran out of replies");
        return next;
      },
    },
  };
}
